export function getUIElements() {
  return {
    startScreen: document.getElementById('startScreen'),
    levelUpScreen: document.getElementById('levelUpScreen'),
    pauseScreen: document.getElementById('pauseScreen'),
    gameOverScreen: document.getElementById('gameOverScreen'),
    startBtn: document.getElementById('startBtn'),
    pauseBtn: document.getElementById('pauseBtn'),
    resumeBtn: document.getElementById('resumeBtn'),
    restartBtn: document.getElementById('restartBtn'),
    upgradeCards: document.getElementById('upgradeCards'),
    hud: document.getElementById('hud'),
    levelText: document.getElementById('levelText'),
    hpFill: document.getElementById('hpFill'),
    xpFill: document.getElementById('xpFill'),
    timerText: document.getElementById('timerText'),
    waveText: document.getElementById('waveText'),
    killsText: document.getElementById('killsText'),
    coresText: document.getElementById('coresText'),
    resultTime: document.getElementById('resultTime'),
    resultKills: document.getElementById('resultKills'),
    resultLevel: document.getElementById('resultLevel'),
    resultCores: document.getElementById('resultCores'),
    bestText: document.getElementById('bestText'),
    toast: document.getElementById('toast'),
    stageText: document.getElementById('stageText'),
    buildTags: document.getElementById('buildTags'),
    constellationStrip: document.getElementById('constellationStrip'),
    dashFill: document.getElementById('dashFill'),
    dashText: document.getElementById('dashText'),
    dashBtn: document.getElementById('dashBtn'),
    debugPanel: document.getElementById('debugPanel'),
  };
}
