export function createRunState(mode = 'menu') {
  const playing = mode === 'playing';
  return {
    mode,
    time: 0,
    wave: 1,
    kills: 0,
    cores: 0,
    spawnTimer: playing ? 0.75 : 0,
    eliteTimer: playing ? 24 : 0,
    directorTimer: playing ? 5.5 : 0,
    directorBudget: 0,
    directorEncounter: 'CALM',
    encounterCount: 0,
    lastEncounterId: '',
    hazardTimer: playing ? 34 : 0,
    hazardTutorialShown: false,
    nextBossAt: 55,
    shake: 0,
    flash: 0,
    enemies: [],
    projectiles: [],
    enemyProjectiles: [],
    gems: [],
    particles: [],
    texts: [],
    stars: [],
    nebulae: [],
    dust: [],
    props: [],
    rings: [],
    banners: [],
    spawnSignals: [],
    afterimages: [],
    hazards: [],
    lastStageIndex: 0,
  };
}

export function createPlayerState(width, height) {
  return {
    x: width / 2,
    y: height / 2,
    r: 18,
    speed: 250,
    hp: 100,
    maxHp: 100,
    level: 1,
    xp: 0,
    xpNeed: 24,
    damage: 24,
    fireRate: 2.7,
    fireTimer: 0,
    bulletSpeed: 700,
    projectileCount: 1,
    spread: 0.16,
    pierce: 0,
    crit: 0.08,
    magnet: 95,
    regen: 0,
    invuln: 0,
    orbitCount: 0,
    orbitDamage: 18,
    orbitRadius: 54,
    orbitSpeed: 2.4,
    novaLevel: 0,
    novaTimer: 7,
    droneLevel: 0,
    droneFireTimer: 0,
    shield: 0,
    lifesteal: 0,
    affinities: { solar: 0, lunar: 0, void: 0, aether: 0, machine: 0 },
    angle: -Math.PI / 2,
    thrust: 0,
    vx: 0,
    vy: 0,
    dashCooldown: 0,
    dashCooldownMax: 1.15,
    dashTimer: 0,
    dashDuration: 0.18,
    dashSpeed: 760,
    dashDirX: 1,
    dashDirY: 0,
    dashAfterimageTimer: 0,
  };
}
